import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const places=JSON.parse(await readFile(new URL('docs/cafe-places.json',root),'utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,label)=>`<a href="${esc(url)}">${esc(label)}</a>`;
const groups=[['village','01 · 母胎村','走進節目的建築場景','私人旅宿，先確認到訪安排，再決定是否列入路線。'],['show','02 · 節目約會咖啡店','一起坐過的咖啡時光','6 間店分布於涯月、翰林、濟州市及安德，可按當日路線挑選。'],['aewol','03 · 涯月咖啡清單','沿著海岸，慢慢喝一杯','10 間不同風格的咖啡與甜點店，喜歡哪間就多留一會。']];
const index=places.map((p,i)=>`<li>${link('#place-'+i,p.name)}</li>`).join('');
const cards=groups.map(([key,eyebrow,title,sub])=>`<section class="cafe-section" id="${key}"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2><p>${sub}</p>${places.map((p,i)=>{
 if(p.group!==key)return '';
 const facts=[['韓文地址',p.address],['營業／到訪時間',p.hours],...(p.closed?[['公休日',p.closed]]:[]),['適合時段（原檔建議）',p.best],...(p.phone?[['電話',p.phone]]:[])];
 const maps='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.ko+' '+p.address);
 const naver=p.naver?'https://map.naver.com/p/entry/place/'+p.naver:'https://map.naver.com/p/search/'+encodeURIComponent(p.ko+' '+p.address);
 return `<article class="cafe-card" id="place-${i}"><span class="cafe-meta">${String(i+1).padStart(2,'0')} · ${esc(p.area)}</span><h3>${esc(p.name)}</h3><p class="cafe-korean">${esc(p.ko)}${p.latin?' · '+esc(p.latin):''}</p>${p.couple?`<p class="cafe-meta">節目組合 · ${esc(p.couple)}</p>`:''}<p class="cafe-intro">${esc(p.intro)}</p><p>${esc(p.detail)}</p>${p.tip?`<aside class="note"><p>${esc(p.tip)}</p></aside>`:''}<dl class="cafe-facts">${facts.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><nav class="cafe-links" aria-label="${esc(p.name)} 地圖及相關連結">${link(maps,'Google Maps ↗')}${link(naver,'NAVER Map ↗')}${p.official?link(p.official,'官方網站 ↗'):''}${p.instagram?link(p.instagram,'Instagram ↗'):''}${p.phone?link('tel:'+p.phone.replace(/[^+\d]/g,''),'致電店舖'):''}${p.day?link(p.day,'查看 Day 1 行程'):''}</nav></article>`;
 }).join('')}</section>`).join('');
const journal=await readFile(new URL('journal.html',root),'utf8');
const nav=journal.match(/<nav class="page-nav"[\s\S]*?<\/nav>/)[0];
const html=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#fffdf9"><meta name="description" content="濟州母胎村、6 間節目約會咖啡店與 10 間涯月咖啡店：特色、韓文地址、營業資訊及地圖。"><title>母胎村・涯月咖啡清單｜濟州小詩生日之旅</title><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="cafes.css"></head><body><main class="paper-page">${nav}<header class="journal-header"><p class="eyebrow">JEJU · COFFEE & LITTLE STOPS</p><h1>一杯咖啡，<br>一段濟州時光。</h1><p class="intro">母胎村・6 間約會咖啡・10 間涯月咖啡</p></header><div class="journal-content"><p>沿著喜歡的場景出發，找一間想坐下的咖啡店。這裡收錄新清單的 17 個地方，方便按當日心情和路線挑選。</p><nav class="cafe-tabs" aria-label="清單分類">${groups.map(([key,label])=>link('#'+key,label)).join('')}</nav><aside class="note"><p>依 2026 年 9 月 7 日《濟州島_母胎單身2及涯月咖啡清單.md》整理；營業時間、節目場景及店舖資料沿用原檔，未重新核對。出發前可透過店舖或地圖確認最新安排。除原有 Randy’s Donuts 行程外，其餘為候選地點，未加入五日固定安排。</p></aside><details class="places"><summary>快速跳到想看的地方 · 17 個地點</summary><ol class="cafe-index">${index}</ol></details>${cards}<section class="cafe-section"><h2>按地區慢慢挑</h2><p><strong>涯月核心咖啡街：</strong>BOMNAL、Team Blow、Tribe、Randy’s Donuts、All That Coffee、Colline、Lazy Pump、Haejigae。</p><p><strong>涯月及濟州市西北一帶：</strong>涯月閑居、Brief Aewol、Goto、Haru Film、Aewol The Sunset、Album Oedo。</p><p><strong>其他區域：</strong>Haehwatang 在翰林；Yuji 在濟州市內陸；Cafe Eulli 在西歸浦安德。地區分組供挑選參考，行車次序可另按當日出發點安排。</p></section><section class="cafe-source"><h2>原檔參考來源</h2><ul><li>${link('https://www.xinmedia.com/article/306088','欣傳媒：母胎村資料')}</li><li>${link('https://www.xinmedia.com/article/306122','欣傳媒：約會咖啡店資料')}</li><li>${link('https://www.funliday.com/posts/jeju_aewol_cafe/','Funliday：涯月咖啡清單')}</li></ul></section></div><footer class="page-footer"><p>Good Drive, Good Days ♡</p></footer></main></body></html>`;
await writeFile(new URL('cafes.html',root),html);
console.log('Rendered 17 detailed place cards with Google Maps and NAVER Map links.');
